/** Viewer-only native-provider entry; no diagnostics, account data or fake results. */
export function filmHTML(nonce){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FlixMomo · GharTV</title><style>
:root{color-scheme:dark;--ink:#f1f7fa;--dim:#a4b7c8;--line:#293b4b;--mint:#9ae7cd}*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 100% 0,#233752 0,transparent 48%),#08111b;color:var(--ink);font:16px/1.6 system-ui,sans-serif}header,main{max-width:1120px;margin:auto;padding:28px}header{display:flex;gap:24px;align-items:center;border-bottom:1px solid var(--line)}header b{font-size:24px;letter-spacing:-1px;margin-right:auto}a{color:var(--mint)}.mark{display:inline-grid;place-items:center;border:1px solid var(--mint);border-radius:10px;width:36px;height:36px;margin-right:10px;color:var(--mint)}main{padding-top:50px}h1{font-size:clamp(36px,5.5vw,68px);line-height:1.08;letter-spacing:-2.5px;margin:16px 0 24px}p{color:var(--dim);max-width:780px}.eyebrow{font-size:11px;letter-spacing:3px;color:var(--mint)}.search{padding:24px;border:1px solid var(--line);border-radius:18px;background:#132231b8;display:flex;flex-wrap:wrap;gap:12px;margin:32px 0 16px}input,select,button,.button{font:inherit;border-radius:10px;border:1px solid #44566b;padding:13px 16px;background:#132231;color:var(--ink);max-width:100%}input{flex:1;min-width:190px}button,.button{cursor:pointer;text-decoration:none}button.primary{background:var(--mint);color:#11281e;border:0;font-weight:750}button:disabled{opacity:.5;cursor:wait}:focus-visible{outline:3px solid var(--mint);outline-offset:4px}.note{padding:18px 22px;border-left:3px solid var(--mint);border-radius:0 12px 12px 0;background:#10272b;max-width:none}.note:empty{display:none}.fine{font-size:13px}.help{margin-top:38px;padding:22px;border:1px solid var(--line);border-radius:14px}.help p{font-size:14px;margin-bottom:0}.status{font-size:13px;color:var(--mint)}summary{cursor:pointer}footer{margin-top:40px;padding:24px 0;border-top:1px solid var(--line);font-size:12px;color:var(--dim)}[hidden]{display:none!important}@media(max-width:600px){header,main{padding:20px}.search{padding:16px;gap:10px}h1{letter-spacing:-1px}.search>*{width:100%}header a{font-size:14px}}
</style></head><body><header><b><span class="mark">G</span>GharTV</b><a href="/">Live television</a></header><main><span class="eyebrow">MOVIES &amp; SERIES · FLIXMOMO</span><h1>Find your next<br>movie night.</h1><p>Search FlixMomo in the browser you already use. Results open on its own website in a new tab; no separate Brave window is needed.</p>
<form class="search" id="search" action="https://flixmomo.app/search" method="get" target="_blank" rel="noopener noreferrer"><input id="query" name="q" placeholder="A film, series or something Punjabi…" aria-label="Movie or series" minlength="2" maxlength="120" required><select id="route" aria-label="Open with"><option value="direct">This browser</option><option value="tor-browser" disabled>Tor Browser</option></select><button class="primary" id="submit" type="submit">Search FlixMomo ↗</button><a class="button" id="browse" href="https://flixmomo.app/" target="_blank" rel="noopener noreferrer">Browse FlixMomo ↗</a></form>
<div id="status" class="status" role="status">Uses your current browser · Nothing to install for direct browsing</div><p id="notice" class="note" role="status" aria-live="polite">Your search stays on FlixMomo. Your Jio account stays in GharTV.</p>
<details class="help"><summary>Opening with Tor Browser</summary><p>Choose Tor Browser to request opening the installed Tor Browser app on this Mac. Connect within that app before browsing. GharTV does not verify its network connection or switch to a direct connection. Tor Browser is optional; ordinary search and browsing use your current browser.</p></details>
<details class="help"><summary>Previously landed on /dummy?</summary><p>Close the old automated browser window and use Search or Browse above. FlixMomo redirects automated browser sessions to that page. These buttons now use normal browser navigation, not automated extraction. Its own verification, sign-in and playback rules still apply.</p></details>
<footer>FlixMomo is a separate provider. Browse content you are entitled to access. GharTV does not control its catalogue or playback availability.</footer></main><script nonce="${nonce}">
const token=${JSON.stringify(nonce)},$=id=>document.getElementById(id);
function message(text){$('notice').textContent=text;}
async function openTor(action){
 $('submit').disabled=true;$('browse').setAttribute('aria-disabled','true');
 try{const response=await fetch('/api/films/'+action,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({route:'tor-browser',query:$('query').value})});const value=await response.json();
 if(!response.ok)throw Error(value.error||'BROWSER_REQUEST_FAILED');
 message('Opening requested in Tor Browser. Connect there if asked, then browse normally. GharTV has not verified the Tor connection.');
 }catch(e){message(e.message==='TOR_BROWSER_NOT_FOUND'?'Tor Browser was not found in Applications. Open your installed Tor Browser yourself, or explicitly choose This browser for a direct connection. Nothing was opened through a fallback route.':'The browser could not be opened. Your query is preserved. Choose This browser to use a direct connection, or open Tor Browser yourself.');}
 finally{$('submit').disabled=false;$('browse').removeAttribute('aria-disabled');}
}
$('search').addEventListener('submit',event=>{
 const q=$('query').value.trim();if(q.length<2||q.length>120||/[\\x00-\\x1f\\x7f]/.test(q)){event.preventDefault();message('Enter 2–120 characters for your search.');return;}
 $('query').value=q;
 if($('route').value==='tor-browser'){event.preventDefault();void openTor('search');}
 else message('Your search opens in a new browser tab on FlixMomo.');
});
$('browse').onclick=event=>{if($('browse').getAttribute('aria-disabled')==='true'){event.preventDefault();return;}if($('route').value==='tor-browser'){event.preventDefault();void openTor('browse');}};
$('route').onchange=()=>{const tor=$('route').value==='tor-browser';$('search').action=tor?'/api/films/native-only':'https://flixmomo.app/search';$('search').method=tor?'post':'get';$('search').target=tor?'_self':'_blank';$('browse').href=tor?'#tor-browser':'https://flixmomo.app/';$('status').textContent=tor?'Native Tor Browser request · No direct fallback':'Uses your current browser · No separate automated session';message(tor?'Search or Browse will request the installed Tor Browser. Connect in that app before continuing.':'Your search opens on FlixMomo in your current browser.');};
$('route').querySelector('option[value="tor-browser"]').disabled=false;
</script></body></html>`;}
