package in.ghartv.nova;

import android.app.Activity;
import android.content.Intent;
import android.os.SystemClock;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import org.json.*;
import org.junit.*;
import org.junit.runner.RunWith;
import java.util.concurrent.*;
import static org.junit.Assert.*;

@RunWith(AndroidJUnit4.class)
public class Review39ExperienceTest {
    Activity activity;WebView web;FrameLayout frame;FilmNativeControls controls;
    private void ui(Runnable r){InstrumentationRegistry.getInstrumentation().runOnMainSync(r);}
    private void launch() {Intent i=new Intent(InstrumentationRegistry.getInstrumentation().getTargetContext(),PreviewHarnessActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);activity=InstrumentationRegistry.getInstrumentation().startActivitySync(i);ui(()->{frame=new FrameLayout(activity);web=new WebView(activity);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setBlockNetworkLoads(true);frame.addView(web,new FrameLayout.LayoutParams(-1,-1));activity.setContentView(frame);});}
    private void page(String path,String html)throws Exception{if(activity==null)launch();String url="https://flixmomo.app"+path;CountDownLatch ready=new CountDownLatch(1);ui(()->{web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){ready.countDown();}});web.loadDataWithBaseURL(url,"<!doctype html><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font:18px sans-serif}button,a,select{display:inline-block;padding:16px;margin:10px}</style><title>Owned Test</title>"+html,"text/html","UTF-8",url);});assertTrue(ready.await(6,TimeUnit.SECONDS));SystemClock.sleep(180);}
    private JSONObject eval(String js)throws Exception{String[] r={null};CountDownLatch l=new CountDownLatch(1);ui(()->web.evaluateJavascript(js,s->{r[0]=s;l.countDown();}));assertTrue(l.await(4,TimeUnit.SECONDS));Object value=new JSONTokener(r[0]).nextValue();assertTrue("Valid JSON from actual WebView, got "+r[0],value instanceof String);return new JSONObject((String)value);}
    private void attach(){ui(()->{View chrome=new TextView(activity);chrome.setVisibility(View.GONE);frame.addView(chrome);controls=new FilmNativeControls(activity,frame,chrome,new FilmNativeControls.Host(){public void navigate(String u){}public void usePage(){web.requestFocus();}public void searchToolbar(){}public void nativeMode(){}public void navigationHint(String s){}});controls.attach(web);web.setFocusableInTouchMode(true);web.requestFocus();});}
    @After public void close(){if(activity!=null){ui(()->{if(controls!=null)controls.destroy();activity.finish();});InstrumentationRegistry.getInstrumentation().waitForIdleSync();}}
    @Test public void allTwelveBadgeDecoratedPlayerButtonsAreDetected()throws Exception{StringBuilder h=new StringBuilder();for(int n=1;n<=12;n++)h.append("<button>PLAYER #").append(n).append(" <span>4K</span><span>BEST</span></button>");page("/watch/one",h.toString());JSONObject s=eval(FilmPageSnapshot.read());assertEquals(12,s.getJSONArray("players").length());assertEquals(12,s.getInt("playerDetectedCount"));assertFalse(s.getBoolean("playerTruncated"));assertEquals("Player 12",s.getJSONArray("players").getJSONObject(11).getString("label"));}
    @Test public void boundsAreReportedInsteadOfPretendingAllSourcesFit()throws Exception{StringBuilder h=new StringBuilder();for(int n=1;n<=55;n++)h.append("<button>Player ").append(n).append("</button>");page("/watch/one",h.toString());JSONObject s=eval(FilmPageSnapshot.read());assertEquals(48,s.getJSONArray("players").length());assertEquals(55,s.getInt("playerDetectedCount"));assertTrue(s.getBoolean("playerTruncated"));}
    @Test public void reorderedPlayersSelectStableIdentityNotOldIndex()throws Exception{String url="https://flixmomo.app/watch/one";page("/watch/one","<button onclick=\"document.title='TWO'\">Player 2 <small>GOOD</small></button><button onclick=\"document.title='ONE'\">Player 1 <span>OG</span></button>");assertEquals("SELECTION_REQUESTED",eval(FilmPageSnapshot.select(url,1,"Player 2")).getString("state"));assertEquals("TWO",eval("JSON.stringify({title:document.title})").getString("title"));}
    @Test public void unrelatedLinksAndNonPlayerLabelsDoNotInflateCount()throws Exception{page("/watch/one","<a href='https://unrelated.invalid/'>Player 1</a><button>Player 2 Download malware</button><button disabled>Player 3</button><button>PLAYER #4 <span>NEW</span></button>");assertEquals(1,eval(FilmPageSnapshot.read()).getJSONArray("players").length());}
    @Test public void titleDescriptionAndStructuredMetadataAreReadWithoutMediaUrls()throws Exception{page("/movie/one","<main><h1>Owned Film</h1><script type='application/ld+json'>{\"@type\":\"Movie\",\"name\":\"Owned Film\",\"description\":\"An original description for a controlled test only.\",\"datePublished\":\"2025-01-02\",\"duration\":\"PT102M\",\"genre\":[\"Adventure\"],\"contentUrl\":\"https://secret.invalid/movie.mp4\"}</script><button>Watch now</button><button>Add to watchlist</button></main>");JSONObject s=eval(FilmPageSnapshot.read()),d=s.getJSONObject("detail");assertEquals("Owned Film",d.getString("title"));assertTrue(d.getBoolean("watch"));assertEquals("Adventure",d.getJSONObject("facts").getString("Genres"));assertFalse(s.toString().contains("secret.invalid"));}
    @Test public void missingDescriptionAndUnavailableActionsStayMissing()throws Exception{page("/movie/one","<h1>Owned Film</h1>");JSONObject d=eval(FilmPageSnapshot.read()).getJSONObject("detail");assertEquals("",d.getString("synopsis"));assertFalse(d.getBoolean("watch"));assertFalse(d.getBoolean("playbackVerified"));}
    @Test public void originRegistryDoesNotTrustLookalikeMigrations(){assertFalse(FilmProviderPolicy.allowed(android.net.Uri.parse("https://flixmomo2.app/movie/one")));assertFalse(FilmProviderPolicy.allowed(android.net.Uri.parse("https://flixmomo.app@evil.invalid/movie/one")));assertTrue(FilmProviderPolicy.allowed(android.net.Uri.parse("https://flixmomo.bet/movie/one")));}
    @Test public void selectedNodeMustStillExistAfterScrollBeforeClick()throws Exception{page("/movie/one","<button id='watch'>Watch now</button>");assertEquals("TAP",eval(FilmPageFocus.script("watch")).getString("state"));eval("(()=>{document.querySelector('#watch').remove();return JSON.stringify({ok:true})})()");assertEquals("STALE",eval(FilmPageFocus.script("commit")).getString("state"));}
    @Test public void coveredTargetCannotReceiveAClick()throws Exception{page("/movie/one","<button id='watch'>Watch now</button>");eval(FilmPageFocus.script("watch"));eval("(()=>{const v=document.createElement('div');v.style='position:fixed;inset:0;z-index:999;background:#123';document.body.append(v);return JSON.stringify({ok:true})})()");assertEquals("OBSCURED",eval(FilmPageFocus.script("commit")).getString("state"));}
    @Test public void immediateRightThenEnterRegistersOneTrustedSave()throws Exception{page("/movie/one","<script>window.saves=0;window.trusted=false</script><button id='watch'>Watch now</button><button id='save' onclick=\"saves++;trusted=event.isTrusted\">Add to watchlist</button>");attach();eval(FilmPageFocus.script("focus"));ui(()->{controls.pageKey(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_RIGHT));controls.pageKey(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_ENTER));});long end=SystemClock.elapsedRealtime()+4000;JSONObject result=null;while(SystemClock.elapsedRealtime()<end){result=eval("JSON.stringify({saves,trusted})");if(result.getInt("saves")>0)break;SystemClock.sleep(40);}assertEquals(result.toString(),1,result.getInt("saves"));assertTrue(result.getBoolean("trusted"));}
    @Test public void offscreenWatchCompletesFromOnePressAfterVisualReadiness()throws Exception{page("/movie/one","<div style='height:1600px'></div><button onclick=\"document.title=event.isTrusted?'WATCHED':'BAD'\">Watch now</button>");attach();ui(()->controls.pageAction("watch"));long end=SystemClock.elapsedRealtime()+4000;String title="";while(SystemClock.elapsedRealtime()<end){title=eval("JSON.stringify({title:document.title})").getString("title");if(title.equals("WATCHED"))break;SystemClock.sleep(40);}assertEquals("WATCHED",title);}
    private Object field(Object o,String n){for(Class<?> c=o.getClass();c!=null;c=c.getSuperclass())try{java.lang.reflect.Field f=c.getDeclaredField(n);f.setAccessible(true);return f.get(o);}catch(NoSuchFieldException e){}catch(Exception e){throw new AssertionError(e);}throw new AssertionError(n);}
    private void nativeActivity()throws Exception{Intent i=new Intent(InstrumentationRegistry.getInstrumentation().getTargetContext(),Review39HarnessActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);activity=InstrumentationRegistry.getInstrumentation().startActivitySync(i);web=(WebView)field(activity,"browser");long end=SystemClock.elapsedRealtime()+6500;int[] count={0};while(SystemClock.elapsedRealtime()<end){ui(()->count[0]=((FilmHomeView)field(activity,"homePanel")).cardCount());if(count[0]>0)break;SystemClock.sleep(40);}assertTrue(count[0]>0);}
    private View text(View v,String label){if(v instanceof TextView&&label.equals(((TextView)v).getText().toString()))return v;if(v instanceof ViewGroup)for(int n=0;n<((ViewGroup)v).getChildCount();n++){View r=text(((ViewGroup)v).getChildAt(n),label);if(r!=null)return r;}return null;}
    private void press(int code){ui(()->{activity.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,code));activity.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_UP,code));});SystemClock.sleep(60);}
    @Test public void nativeTitleHasMetadataVisibleFocusAndExplicitOriginalPage()throws Exception{nativeActivity();ui(()->((FilmHomeView)field(activity,"homePanel")).focusRefresh());press(KeyEvent.KEYCODE_DPAD_DOWN);press(KeyEvent.KEYCODE_DPAD_CENTER);FilmDetailView d=(FilmDetailView)field(activity,"detailPanel");long end=SystemClock.elapsedRealtime()+5000;String[] title={""};while(SystemClock.elapsedRealtime()<end){ui(()->title[0]=d.currentTitle());if(title[0].equals("The Glass Mountain"))break;SystemClock.sleep(40);}ui(()->{assertEquals(View.VISIBLE,d.getVisibility());assertEquals("The Glass Mountain",d.currentTitle());assertFalse(web.isFocusable());assertNotNull(activity.getCurrentFocus());assertNotNull(text(d,"Watch now"));assertNotNull(text(d,"Original page"));});
        SystemClock.sleep(150);android.graphics.Bitmap shot=InstrumentationRegistry.getInstrumentation().getUiAutomation().takeScreenshot();assertNotNull(shot);try(java.io.FileOutputStream out=new java.io.FileOutputStream(new java.io.File(activity.getExternalFilesDir(null),"review39-native-title-fixture.png"))){shot.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}shot.recycle();
    }
    @Test public void searchStaysNativeWithAttributionAndPosterCards()throws Exception{nativeActivity();ui(()->{((EditText)field(activity,"query")).setText("Glass Mountain");text(activity.getWindow().getDecorView(),"Search").performClick();});long end=SystemClock.elapsedRealtime()+5000;int[] count={0};while(SystemClock.elapsedRealtime()<end){ui(()->count[0]=((FilmHomeView)field(activity,"homePanel")).cardCount());if(count[0]>0)break;SystemClock.sleep(40);}ui(()->{assertTrue(count[0]>0);assertEquals(View.VISIBLE,((FilmHomeView)field(activity,"homePanel")).getVisibility());assertFalse(web.isFocusable());assertNotNull(text(activity.getWindow().getDecorView(),FilmProviderPolicy.CREDIT));assertTrue(web.getUrl().contains("/search?q="));});}
    @Test public void leavingNativeDetailExplicitlyRestoresOriginalBrowser()throws Exception{nativeActivity();ui(()->((FilmHomeView)field(activity,"homePanel")).focusRefresh());press(KeyEvent.KEYCODE_DPAD_DOWN);press(KeyEvent.KEYCODE_DPAD_CENTER);ui(()->{FilmDetailView d=(FilmDetailView)field(activity,"detailPanel");assertEquals(View.VISIBLE,d.getVisibility());text(d,"Original page").performClick();assertEquals(View.GONE,d.getVisibility());assertTrue(web.isFocusable());assertTrue(web.hasFocus());});}
}
