package in.ghartv.nova;
import android.app.Activity;
import android.content.Intent;
import android.os.SystemClock;
import android.view.*;
import android.webkit.WebView;
import android.widget.*;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import org.json.*;
import org.junit.*;
import org.junit.runner.RunWith;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import static org.junit.Assert.*;

/** Uses the actual native view lifecycle after layout, and actual Activity pointer dispatch. */
@RunWith(AndroidJUnit4.class)
public class Review44LoadingMouseTest {
 Activity activity; WebView web;
 void ui(Runnable r){InstrumentationRegistry.getInstrumentation().runOnMainSync(r);}
 Object field(Object o,String n){for(Class<?> c=o.getClass();c!=null;c=c.getSuperclass())try{java.lang.reflect.Field f=c.getDeclaredField(n);f.setAccessible(true);return f.get(o);}catch(NoSuchFieldException e){}catch(Exception e){throw new AssertionError(e);}throw new AssertionError(n);}
 View text(View v,String label){if(v instanceof TextView&&label.equals(((TextView)v).getText().toString()))return v;if(v instanceof ViewGroup)for(int n=0;n<((ViewGroup)v).getChildCount();n++){View x=text(((ViewGroup)v).getChildAt(n),label);if(x!=null)return x;}return null;}
 void key(int action,int code){ui(()->activity.dispatchKeyEvent(new KeyEvent(action,code)));}
 void press(int code){key(KeyEvent.ACTION_DOWN,code);SystemClock.sleep(65);key(KeyEvent.ACTION_UP,code);SystemClock.sleep(50);}
 void start(){activity=InstrumentationRegistry.getInstrumentation().startActivitySync(new Intent(InstrumentationRegistry.getInstrumentation().getTargetContext(),PreviewHarnessActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));}
 JSONObject cards(int n)throws Exception{JSONArray a=new JSONArray();for(int i=0;i<n;i++)a.put(new JSONObject().put("url","https://flixmomo.app/movie/owned-"+i).put("title","Owned "+i).put("image","https://image.tmdb.org/owned-"+i+".png").put("metadata","Owned test metadata"));return new JSONObject().put("results",a);}
 FilmHomeView home(AtomicInteger loads){return new FilmHomeView(activity,new FilmHomeView.Host(){public void open(String u){}public void refresh(){}public void provider(){}public void privacy(){}},(v,u)->{loads.incrementAndGet();v.setImageDrawable(new android.graphics.drawable.ColorDrawable(0xff345678));});}
 void waitLoads(AtomicInteger n,int lower){long end=SystemClock.elapsedRealtime()+3500;while(n.get()<lower&&SystemClock.elapsedRealtime()<end)SystemClock.sleep(25);assertTrue("Artwork should load without a scroll, got "+n.get(),n.get()>=lower);}
 JSONObject eval(String js)throws Exception{String[] s={null};CountDownLatch l=new CountDownLatch(1);ui(()->web.evaluateJavascript(js,v->{s[0]=v;l.countDown();}));assertTrue(l.await(5,TimeUnit.SECONDS));return new JSONObject((String)new JSONTokener(s[0]).nextValue());}
 @After public void close(){if(activity!=null)ui(()->activity.finish());}
 @Test public void delayedCardsInAlreadyLaidOutPanelLoadWithoutScrolling()throws Exception{start();AtomicInteger n=new AtomicInteger();FilmHomeView[] h={null};ui(()->{h[0]=home(n);activity.setContentView(h[0]);});SystemClock.sleep(250);JSONObject rows=cards(60);ui(()->h[0].render(rows));waitLoads(n,4);assertTrue(n.get()<30);assertEquals(0,((ScrollView)field(h[0],"scroll")).getScrollY());}
 @Test public void renderedHiddenPanelLoadsWhenShown()throws Exception{start();AtomicInteger n=new AtomicInteger();FilmHomeView[] h={null};JSONObject rows=cards(20);ui(()->{h[0]=home(n);activity.setContentView(h[0]);h[0].setVisibility(View.GONE);h[0].render(rows);});SystemClock.sleep(180);assertEquals(0,n.get());ui(()->h[0].setVisibility(View.VISIBLE));waitLoads(n,4);}
 @Test public void refreshReplacementAtSameOuterSizeStartsNewArtwork()throws Exception{start();AtomicInteger n=new AtomicInteger();FilmHomeView[] h={null};JSONObject rows=cards(12);ui(()->{h[0]=home(n);activity.setContentView(h[0]);h[0].render(rows);});waitLoads(n,4);int before=n.get();ui(()->{h[0].discardSuggestions();h[0].render(rows);});waitLoads(n,before+4);}
 @Test public void earlyEmptySnapshotRemainsLoadingAndCannotRefreshTwice()throws Exception{start();FilmHomeView[] h={null};JSONObject empty=cards(0);ui(()->{h[0]=home(new AtomicInteger());activity.setContentView(h[0]);h[0].loading();h[0].render(empty);assertTrue(h[0].isLoadingData());assertFalse(text(h[0],"Refresh suggestions").isEnabled());assertFalse(text(h[0],"Open provider page").isEnabled());assertTrue(text(h[0],"Privacy & content use").isEnabled());assertEquals(View.VISIBLE,((ProgressBar)field(h[0],"progress")).getVisibility());assertTrue(((TextView)field(h[0],"status")).getText().toString().contains("Loading"));});}
 @Test public void actualSuggestionsEndLoadingAndEnableActions()throws Exception{start();JSONObject rows=cards(5);ui(()->{FilmHomeView h=home(new AtomicInteger());activity.setContentView(h);h.loading();h.render(rows);assertFalse(h.isLoadingData());assertTrue(text(h,"Refresh suggestions").isEnabled());assertEquals(View.GONE,((ProgressBar)field(h,"progress")).getVisibility());});}
 @Test public void timeoutIsRecoverableNotAFalseEmptyCatalogue(){start();ui(()->{FilmHomeView h=home(new AtomicInteger());activity.setContentView(h);h.loading();((Runnable)field(h,"loadingDeadline")).run();assertFalse(h.isLoadingData());assertTrue(text(h,"Refresh suggestions").isEnabled());assertTrue(((TextView)field(h,"status")).getText().toString().contains("taking longer"));});}
 @Test public void explicitFailureReleasesLoadingActions(){start();ui(()->{FilmHomeView h=home(new AtomicInteger());activity.setContentView(h);h.loading();h.unavailable("Connection failed");assertFalse(h.isLoadingData());assertTrue(text(h,"Open provider page").isEnabled());});}
 @Test public void titleShowsSeedImmediatelyButDoesNotEnableWatchBeforeObservation()throws Exception{start();JSONObject card=new JSONObject().put("title","Owned Title").put("metadata","2025 · locally authored fixture");ui(()->{FilmDetailView d=new FilmDetailView(activity,new FilmDetailView.Host(){public void watch(){}public void watchlist(){}public void original(){}public void back(){}});activity.setContentView(d);d.begin("https://flixmomo.app/movie/owned",card);assertEquals("Owned Title",d.currentTitle());assertTrue(((TextView)field(d,"facts")).getText().toString().contains("2025"));assertFalse(text(d,"Watch now").isEnabled());assertEquals(View.VISIBLE,((ProgressBar)field(d,"progress")).getVisibility());});}
 void player()throws Exception{
  activity=InstrumentationRegistry.getInstrumentation().startActivitySync(new Intent(InstrumentationRegistry.getInstrumentation().getTargetContext(),Review42HarnessActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));web=(WebView)field(activity,"browser");
  long end=SystemClock.elapsedRealtime()+7000;boolean[] ready={false};while(SystemClock.elapsedRealtime()<end){ui(()->ready[0]=((FilmHomeView)field(activity,"homePanel")).cardCount()>0);if(ready[0])break;SystemClock.sleep(40);}assertTrue(ready[0]);
  ui(()->((FilmHomeView)field(activity,"homePanel")).focusRefresh());press(KeyEvent.KEYCODE_DPAD_DOWN);press(KeyEvent.KEYCODE_DPAD_CENTER);
  ready[0]=false;end=SystemClock.elapsedRealtime()+5000;while(SystemClock.elapsedRealtime()<end){ui(()->ready[0]=text((View)field(activity,"detailPanel"),"Watch now").isEnabled());if(ready[0])break;SystemClock.sleep(40);}assertTrue(ready[0]);
  ui(()->text((View)field(activity,"detailPanel"),"Watch now").requestFocus());press(KeyEvent.KEYCODE_DPAD_CENTER);
  end=SystemClock.elapsedRealtime()+6000;while(SystemClock.elapsedRealtime()<end){if(eval("JSON.stringify({p:location.pathname})").optString("p").equals("/watch/lantern"))break;SystemClock.sleep(40);}assertEquals("/watch/lantern",eval("JSON.stringify({p:location.pathname})").getString("p"));SystemClock.sleep(2200);
 }
 void mouse(){ui(()->((FilmNativeControls)field(activity,"nativeControls")).menu());ui(()->{View m=text((View)field(field(activity,"nativeControls"),"tray"),"Mouse");assertNotNull(m);m.requestFocus();});press(KeyEvent.KEYCODE_DPAD_CENTER);}
 @Test public void trayMouseEntersPointerWithoutNativeControlsStealingFocus()throws Exception{player();mouse();ui(()->{assertTrue((Boolean)field(activity,"mouseActive"));assertTrue(((RemoteWebCursor)field(activity,"cursor")).enabled());assertFalse(((FilmNativeControls)field(activity,"nativeControls")).visible());assertTrue(web.hasFocus());assertFalse((Boolean)field(field(activity,"nativeControls"),"active"));});}
 @Test public void pointerMovesWithRemoteAndBackReturnsToTray()throws Exception{player();mouse();RemoteCursorState s=(RemoteCursorState)field(field(activity,"cursor"),"state");float x=s.x();key(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_RIGHT);SystemClock.sleep(250);key(KeyEvent.ACTION_UP,KeyEvent.KEYCODE_DPAD_RIGHT);assertTrue(s.x()>x);press(KeyEvent.KEYCODE_BACK);ui(()->{assertFalse((Boolean)field(activity,"mouseActive"));assertTrue(((FilmNativeControls)field(activity,"nativeControls")).ownsFocus());});}
 @Test public void mousePressStartsActualOwnedVideoInTheSameWebView()throws Exception{player();mouse();JSONObject pos=eval("JSON.stringify((()=>{const v=document.querySelector('video');v.pause();v.currentTime=0;window.trustedMedia=false;v.scrollIntoView({block:'center'});const r=v.getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2,w:innerWidth,h:innerHeight}})())");SystemClock.sleep(180);ui(()->{RemoteCursorState s=(RemoteCursorState)field(field(activity,"cursor"),"state");s.position((float)(pos.optDouble("x")*web.getWidth()/pos.optDouble("w")),(float)(pos.optDouble("y")*web.getHeight()/pos.optDouble("h")));});press(KeyEvent.KEYCODE_DPAD_CENTER);JSONObject out=new JSONObject();long end=SystemClock.elapsedRealtime()+6000;while(SystemClock.elapsedRealtime()<end){out=eval("JSON.stringify({time:document.querySelector('video').currentTime,paused:document.querySelector('video').paused,trusted:!!window.trustedMedia})");if(out.optDouble("time")>.35&&!out.optBoolean("paused"))break;SystemClock.sleep(50);}assertTrue(out.toString(),out.optDouble("time")>.35);assertTrue(out.getBoolean("trusted"));assertFalse(out.getBoolean("paused"));}
 @Test public void nativeCardReturnDoesNotReloadUnderlyingProvider()throws Exception{player();ui(()->{((FilmNativeControls)field(activity,"nativeControls")).hideAll();});String before=eval("JSON.stringify({p:location.pathname})").getString("p");ui(()->{try{java.lang.reflect.Method m=FlixMomoActivity.class.getDeclaredMethod("returnToCards");m.setAccessible(true);m.invoke(activity);}catch(Exception e){throw new AssertionError(e);}});SystemClock.sleep(250);assertEquals(before,eval("JSON.stringify({p:location.pathname})").getString("p"));}
}
